### PR TITLE
Fix local Whisper dictation race and stabilize stop/transcription flow

### LINKED ISSUE #146: Local Whisper STT fails due to pipecat's hardcoded 10-second heartbeat timeout
### Problem
Local Whisper on CPU takes ~24 seconds to transcribe, but pipecat has a hardcoded 10-second heartbeat timeout that resets the connection before transcription completes.

### Root Cause
In pipecat's `task.py`, the timeout is computed at import time:
```python
HEARTBEAT_MONITOR_SECS = HEARTBEAT_SECS * 10  # Always 10 seconds

### PR DESCRIPTION
**Pull request by seerapubhavyareddy**
## Summary
This PR fixes a timing race in local dictation where slow Whisper transcription could arrive after the recording flow had already transitioned to idle, causing transcription to be dropped and not inserted.

### What changed
- Updated turn finalization logic to keep the turn alive in a draining state when STT finalization is slow, so late Whisper results are still processed.
- Prevented duplicate stop handling while already in processing to avoid unnecessary stop churn.
- Switched local Whisper defaults to a faster runtime profile for better real-time stability:
  - `model: "small"`
  - `compute_type: "int8"`

### Why this fix
In local Whisper + Ollama setups, transcription latency can be higher than cloud STT providers.  
The previous stop-time transition could complete too early, creating a race where valid transcription arrived "too late" and was ignored.

## Impact
- Improves reliability of local dictation with Whisper.
- Reduces missed transcriptions after stop.
- Stabilizes stop-to-insert behavior in slower local environments.

## Validation
- Reproduced issue locally before fix (transcription observed but dropped due to state timing).
- Verified post-fix runs repeatedly follow the expected completion path:
  - stop -> draining -> transcription observed -> turn end emitted -> raw-transcription emitted -> client receives raw-transcription
- Frontend test suite passes:
  - `corepack pnpm test`
  - `3` test files, `48` tests passed

## Notes
- No heartbeat configuration changes were required for this fix.
- Changes are focused on state/timing correctness and local Whisper runtime defaults.

Closes #146

### CODE REVIEW

**Review by kstonekuan — CHANGES_REQUESTED** [review]

File: app/src/OverlayApp.tsx [hunk 1]
```diff
@@ -519,6 +519,10 @@ function RecordingControl() {
 	]);
 
 	const onStopRecording = useCallback(() => {
+		if (displayState === "processing") {
+			return;
+		}
+
 		setIsMicAcquiring(false);
```
Comment (kstonekuan) [inline app/src/OverlayApp.tsx]: Why did you add this return here?

**Review by kstonekuan — APPROVED** [review]
LGTM, thanks for going through the review cycle!
